// vue/day11/todolist/src/components/TodoList.vue
<template>
  <div>
    <Todo
      v-for="(todo,idx) in todos"
      :key="idx"
      :todo="todo"
    />
  </div>
</template>

<script>
import {mapState} from 'vuex'
import Todo from '@/components/Todo'
export default {
  name:'TodoList',
  components: {
    Todo
  },
  computed: {
    ...mapState([
      'todos',
    ])
  }
}
</script>

<style>

</style>

// react/react10/src/components/TodoList.js
import React from 'react'
import TodoListItem from './TodoListItem'
import './TodoList.scss'

function TodoList({todos,onRemove,onToggle}) {
  return (
    <div className="TodoList">
      {todos.map(todo=>(
        <TodoListItem 
          todo={todo} 
          key={todo.id} 
          onRemove={onRemove} 
          onToggle={onToggle}/>
      ))}
    </div>
  )
};

export default React.memo(TodoList);
